import { defineConfig } from 'tsup';

export default defineConfig([
  {
    entry: ["./src/styles/*"],
    splitting: false,
    sourcemap: false,
    clean: true,
    minify: false,
    dts: false,
    skipNodeModulesBundle: true,
    external: ["node_modules"],
    outDir: "dist/styles",
  },
  {
    entry: ['src/components/ui/*'],
    format: ['cjs', 'esm'],
    dts: true,
    splitting: false,
    sourcemap: true,
    clean: true,
    external: ["node_modules"],
    treeshake: false,
    minify: false,
    outDir: 'dist/components/ui',
  },
  {
    entry: ['src/lib/*'],
    format: ['cjs', 'esm'],
    dts: true,
    splitting: false,
    sourcemap: true,
    clean: true,
    external: ["node_modules"],
    treeshake: true,
    minify: true,
    outDir: 'dist/lib',
  },
  {
    entry: ['src/hooks/*'],
    format: ['cjs', 'esm'],
    dts: true,
    splitting: false,
    sourcemap: true,
    clean: true,
    external: ["node_modules"],
    treeshake: true,
    minify: true,
    outDir: 'dist/hooks',
  }
]);
